import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { AssignmentDeedData } from "@/deeds/types";
import { format } from "date-fns";

const styles = StyleSheet.create({
  page: { fontFamily: "Helvetica", fontSize: 10, paddingTop: 60, paddingBottom: 60, paddingLeft: 72, paddingRight: 72, lineHeight: 1.5, color: "#1a1a1a" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  subtitle: { fontSize: 12, color: "#555", marginBottom: 32 },
  sectionHeading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 20, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.5, color: "#333" },
  clauseHeading: { fontSize: 10, fontFamily: "Helvetica-Bold", marginTop: 12, marginBottom: 3 },
  para: { fontSize: 10, marginBottom: 6, lineHeight: 1.6 },
  small: { fontSize: 8, color: "#666", marginBottom: 4 },
  disclaimer: { fontSize: 8, backgroundColor: "#fff3cd", padding: 10, borderRadius: 3, marginBottom: 20, color: "#856404", lineHeight: 1.5 },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ddd", paddingVertical: 5 },
  tableLabel: { width: "40%", color: "#555", fontSize: 9 },
  tableValue: { width: "60%", fontFamily: "Helvetica-Bold", fontSize: 9 },
  signatureLine: { borderBottomWidth: 0.5, borderBottomColor: "#333", marginBottom: 4, height: 20 },
  signatureLabel: { fontSize: 9, color: "#555", marginBottom: 16 },
  footer: { position: "absolute", bottom: 30, left: 72, right: 72, fontSize: 8, color: "#999", textAlign: "center" },
  pageNumber: { position: "absolute", bottom: 30, right: 72, fontSize: 8, color: "#999" },
  hr: { borderBottomWidth: 0.5, borderBottomColor: "#ccc", marginVertical: 14 },
  bold: { fontFamily: "Helvetica-Bold" },
  amountHighlight: { fontFamily: "Helvetica-Bold", fontSize: 11 },
  highlight: { backgroundColor: "#e8f4f8", padding: 8, marginBottom: 8, borderRadius: 2 },
});

function formatAud(cents: number) {
  return new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(cents / 100);
}

export function AssignmentDeedDocument({ data }: { data: AssignmentDeedData }) {
  const clauses = data.stateSpecificClauses;

  return (
    <Document title={`Assignment Deed — ${data.propertyAddress}`} author="OptionFlow" subject="Assignment of Call Option Deed">
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.title}>DEED OF ASSIGNMENT OF CALL OPTION</Text>
        <Text style={styles.subtitle}>{data.state} — {data.propertyAddress}, {data.suburb}</Text>

        <View style={styles.disclaimer}>
          <Text style={[styles.bold, { fontSize: 8 }]}>IMPORTANT LEGAL NOTICE</Text>
          <Text style={{ fontSize: 8, marginTop: 3 }}>
            This document is a commercial template generated by OptionFlow and does not constitute legal advice.
            All parties should obtain independent legal advice from a qualified solicitor before signing.
            This deed is subject to {clauses.contractActRef}.
            {"\n"}Generated: {format(data.generatedAt, "d MMMM yyyy 'at' h:mm a")}
            {data.platformAbn ? `\nOptionFlow ABN: ${data.platformAbn}` : ""}
          </Text>
        </View>

        <Text style={styles.sectionHeading}>PARTIES</Text>
        <View style={{ marginBottom: 16 }}>
          <Text style={[styles.small, { marginBottom: 2 }]}>ASSIGNOR</Text>
          <Text style={styles.bold}>{data.assignor_legalName}</Text>
          {data.assignor_abn && <Text style={styles.small}>ABN: {data.assignor_abn}</Text>}
          <Text style={styles.para}>{data.assignor_address}</Text>
        </View>
        <View style={{ marginBottom: 16 }}>
          <Text style={[styles.small, { marginBottom: 2 }]}>ASSIGNEE</Text>
          <Text style={styles.bold}>{data.assignee_legalName}</Text>
          {data.assignee_abn && <Text style={styles.small}>ABN: {data.assignee_abn}</Text>}
          <Text style={styles.para}>{data.assignee_address}</Text>
        </View>

        <View style={styles.hr} />

        <Text style={styles.sectionHeading}>KEY TERMS</Text>
        <View style={{ marginBottom: 16 }}>
          {[
            ["Property", `${data.propertyAddress}, ${data.suburb} ${data.state} ${data.postcode}`],
            ["Original Option Price", formatAud(data.originalOptionPrice)],
            ["Assignment Consideration", formatAud(data.assignmentPrice)],
            ["Developer Deposit", formatAud(data.developerDeposit)],
            ["Assignment Date", format(data.assignmentDate, "d MMMM yyyy")],
            ["Completion Date", format(data.completionDate, "d MMMM yyyy")],
          ].map(([label, value]) => (
            <View key={label} style={styles.tableRow}>
              <Text style={styles.tableLabel}>{label}</Text>
              <Text style={styles.tableValue}>{value}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.sectionHeading}>RECITALS</Text>
        <Text style={styles.para}>
          A. The Assignor holds a call option (the <Text style={styles.bold}>Original Option</Text>) to purchase the Property at the Original Option Price pursuant to a Call Option Deed.
        </Text>
        <Text style={styles.para}>
          B. The Assignee wishes to acquire the Assignor&apos;s rights under the Original Option.
        </Text>
        <Text style={styles.para}>
          C. The Assignor has agreed to assign all its rights, title, and interest in the Original Option to the Assignee for the Assignment Consideration.
        </Text>

        <Text style={styles.sectionHeading}>OPERATIVE PROVISIONS</Text>

        <Text style={styles.clauseHeading}>1. ASSIGNMENT</Text>
        <Text style={styles.para}>
          1.1 In consideration of the Assignment Consideration payable by the Assignee, the Assignor hereby assigns to the Assignee all its rights, title, and interest in and under the Original Option with effect from the Assignment Date.
        </Text>
        <Text style={styles.para}>
          1.2 From the Assignment Date, the Assignee shall be entitled to exercise the Original Option in its own name and shall be bound by all obligations of the Assignor under the Original Option as if the Assignee were originally named as the Grantee.
        </Text>

        <Text style={styles.clauseHeading}>2. CONSIDERATION</Text>
        <Text style={styles.para}>
          2.1 The Assignee shall pay the <Text style={styles.bold}>Assignment Consideration</Text> of <Text style={styles.amountHighlight}>{formatAud(data.assignmentPrice)}</Text> to the Assignor as follows: (a) a deposit of {formatAud(data.developerDeposit)} on execution of this deed; (b) the balance on or before the Completion Date.
        </Text>

        <Text style={styles.clauseHeading}>3. ASSIGNEE'S WARRANTIES</Text>
        <Text style={styles.para}>
          3.1 The Assignee warrants that: (a) it has obtained independent legal and financial advice in relation to this assignment; (b) it has reviewed the Original Option and accepts all its terms; (c) it has the legal capacity and authority to enter into this deed.
        </Text>

        <Text style={styles.clauseHeading}>4. STAMP DUTY</Text>
        <Text style={styles.para}>{clauses.stampDutyNote}</Text>

        <Text style={styles.clauseHeading}>5. GENERAL</Text>
        <Text style={styles.para}>
          5.1 This deed constitutes the entire agreement between the parties in relation to its subject matter.
          5.2 This deed is governed by the laws of {data.state === "ACT" ? "the Australian Capital Territory" : data.state}.
        </Text>

        <Text style={styles.sectionHeading}>EXECUTION</Text>
        <Text style={styles.small}>{clauses.witnessRequirements}</Text>

        <View style={{ marginTop: 20, flexDirection: "row", gap: 40 }}>
          <View style={{ flex: 1 }}>
            <Text style={[styles.bold, { fontSize: 10, marginBottom: 8 }]}>SIGNED by ASSIGNOR</Text>
            <Text style={styles.small}>{data.assignor_legalName}</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Signature / Authorised Signatory</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Full name / Date</Text>
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[styles.bold, { fontSize: 10, marginBottom: 8 }]}>SIGNED by ASSIGNEE</Text>
            <Text style={styles.small}>{data.assignee_legalName}</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Signature / Authorised Signatory</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Full name / Date</Text>
          </View>
        </View>

        <Text style={styles.footer} render={() => `Assignment Deed — ${data.propertyAddress} — Generated by OptionFlow`} fixed />
        <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} fixed />
      </Page>
    </Document>
  );
}
