import { AlertTriangle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

export function LegalDisclaimer({ dismissible = false }: { dismissible?: boolean }) {
  return (
    <Alert variant="destructive" className="border-amber-500 bg-amber-50 text-amber-900">
      <AlertTriangle className="h-4 w-4 !text-amber-600" />
      <AlertDescription className="text-sm">
        <strong>Legal Disclaimer:</strong> Documents generated by this platform are commercial templates only and do not constitute legal advice. You should obtain independent legal advice from a qualified solicitor before signing any option deed or assignment deed. Property options are regulated — ensure compliance with your state&apos;s legislation.{" "}
        <a href="/legal/disclaimer" className="underline font-medium">
          Read full disclaimer
        </a>
      </AlertDescription>
    </Alert>
  );
}
