import Link from "next/link";
import { Building2 } from "lucide-react";

export default function LegalDisclaimerPage() {
  return (
    <div className="min-h-screen bg-zinc-50">
      <header className="border-b bg-white">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <Building2 className="h-5 w-5 text-blue-600" />
            <span className="font-bold text-zinc-900">Devbud.</span>
          </Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-zinc-900 mb-2">Legal Disclaimer</h1>
        <p className="text-zinc-500 mb-8">Last updated: {new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
          <p className="font-semibold text-amber-900">
            IMPORTANT: The documents and information provided by Devbud. do not constitute legal advice. You should always obtain independent legal advice from a qualified solicitor before signing any option deed, assignment deed, or contract for the sale of land.
          </p>
        </div>

        <div className="prose prose-zinc max-w-none space-y-6 text-sm text-zinc-700">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900 mb-3">1. No Legal Advice</h2>
            <p>Devbud. is a technology platform that facilitates property option transactions. We are not solicitors and we do not provide legal advice. The deed templates generated by this platform are commercial templates based on common Australian property practice and are provided for reference purposes only.</p>
            <p className="mt-3">Before signing any document generated by this platform, you should seek independent legal advice from a qualified Australian property solicitor.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 mb-3">2. State and Territory Laws</h2>
            <p>Property law in Australia differs between states and territories. While we endeavour to provide state-specific templates, we cannot guarantee that any template will comply with all current legal requirements in your jurisdiction. Laws change frequently.</p>
            <div className="mt-3 space-y-1">
              {[
                ["NSW", "https://www.lsc.nsw.gov.au", "NSW Law Society"],
                ["VIC", "https://www.liv.asn.au", "Law Institute of Victoria"],
                ["QLD", "https://www.qls.com.au", "Queensland Law Society"],
                ["WA", "https://www.lawsocietywa.asn.au", "Law Society of WA"],
                ["SA", "https://www.lawsocietysa.asn.au", "Law Society of SA"],
                ["TAS", "https://www.lawtas.org.au", "Law Society of Tasmania"],
                ["ACT", "https://www.actlawsociety.asn.au", "ACT Law Society"],
                ["NT", "https://www.lawsocietynt.asn.au", "Law Society NT"],
              ].map(([state, href, label]) => (
                <div key={state} className="flex items-center gap-2">
                  <span className="font-medium w-8 text-zinc-500">{state}</span>
                  <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">{label}</a>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 mb-3">3. Option and Assignment Deeds</h2>
            <p>Call option deeds and assignment deeds are legally binding documents when executed. They create real rights and obligations. The use of an option structure does not eliminate stamp duty, land tax, or other regulatory requirements — these vary by state and by the specific transaction structure.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 mb-3">4. No Warranty</h2>
            <p>Devbud. makes no warranty, express or implied, as to the accuracy, completeness, or fitness for purpose of any document template or information provided on this platform. To the maximum extent permitted by law, Devbud. excludes all liability for any loss or damage arising from reliance on documents generated by this platform.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900 mb-3">5. Contact</h2>
            <p>If you have questions about any legal aspect of a transaction, please consult a qualified property solicitor in the relevant state or territory.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
