import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import type { OptionDeedData } from "@/deeds/types";
import { format } from "date-fns";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 60,
    paddingBottom: 60,
    paddingLeft: 72,
    paddingRight: 72,
    lineHeight: 1.5,
    color: "#1a1a1a",
  },
  coverPage: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 80,
    paddingBottom: 80,
    paddingLeft: 72,
    paddingRight: 72,
    lineHeight: 1.5,
  },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", marginBottom: 6, color: "#1a1a1a" },
  subtitle: { fontSize: 12, color: "#555", marginBottom: 32 },
  sectionHeading: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 20, marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.5, color: "#333" },
  clauseHeading: { fontSize: 10, fontFamily: "Helvetica-Bold", marginTop: 12, marginBottom: 3 },
  para: { fontSize: 10, marginBottom: 6, lineHeight: 1.6 },
  small: { fontSize: 8, color: "#666", marginBottom: 4 },
  disclaimer: { fontSize: 8, backgroundColor: "#fff3cd", padding: 10, borderRadius: 3, marginBottom: 20, color: "#856404", lineHeight: 1.5 },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ddd", paddingVertical: 5 },
  tableLabel: { width: "40%", color: "#555", fontSize: 9 },
  tableValue: { width: "60%", fontFamily: "Helvetica-Bold", fontSize: 9 },
  signatureBlock: { marginTop: 30, borderTopWidth: 0.5, borderTopColor: "#333", paddingTop: 8 },
  signatureLabel: { fontSize: 9, color: "#555", marginBottom: 16 },
  signatureLine: { borderBottomWidth: 0.5, borderBottomColor: "#333", marginBottom: 4, height: 20 },
  footer: { position: "absolute", bottom: 30, left: 72, right: 72, fontSize: 8, color: "#999", textAlign: "center" },
  pageNumber: { position: "absolute", bottom: 30, right: 72, fontSize: 8, color: "#999" },
  hr: { borderBottomWidth: 0.5, borderBottomColor: "#ccc", marginVertical: 14 },
  bold: { fontFamily: "Helvetica-Bold" },
  amountHighlight: { fontFamily: "Helvetica-Bold", fontSize: 11 },
});

function formatAud(cents: number) {
  return new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(cents / 100);
}

export function OptionDeedDocument({ data }: { data: OptionDeedData }) {
  const clauses = data.stateSpecificClauses;

  return (
    <Document
      title={`Call Option Deed — ${data.propertyAddress}`}
      author="OptionFlow"
      subject="Call Option Deed"
      creator="OptionFlow Platform"
      producer="OptionFlow"
    >
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <View style={{ flex: 1, justifyContent: "center" }}>
          <Text style={styles.title}>CALL OPTION DEED</Text>
          <Text style={styles.subtitle}>{data.state} — {data.propertyAddress}, {data.suburb}</Text>

          <View style={styles.hr} />

          <View style={{ marginBottom: 24 }}>
            <Text style={[styles.small, { marginBottom: 2 }]}>GRANTOR (Property Owner)</Text>
            <Text style={styles.bold}>{data.grantor_legalName}</Text>
            <Text style={styles.para}>{data.grantor_address}</Text>
          </View>

          <View style={{ marginBottom: 24 }}>
            <Text style={[styles.small, { marginBottom: 2 }]}>GRANTEE (Option Holder)</Text>
            <Text style={styles.bold}>{data.grantee_legalName}</Text>
            <Text style={styles.para}>{data.grantee_address}</Text>
          </View>

          <View style={styles.hr} />

          <View style={{ marginBottom: 20 }}>
            {[
              ["Option Price", formatAud(data.optionPrice)],
              ["Option Fee", formatAud(data.optionFeeAmount)],
              ["Commencement Date", format(data.commencementDate, "d MMMM yyyy")],
              ["Expiry Date", format(data.expiryDate, "d MMMM yyyy")],
            ].map(([label, value]) => (
              <View key={label} style={styles.tableRow}>
                <Text style={styles.tableLabel}>{label}</Text>
                <Text style={styles.tableValue}>{value}</Text>
              </View>
            ))}
          </View>

          <View style={styles.disclaimer}>
            <Text style={[styles.bold, { fontSize: 8 }]}>IMPORTANT LEGAL NOTICE</Text>
            <Text style={{ fontSize: 8, marginTop: 3 }}>
              This document is a commercial template generated by OptionFlow and does not constitute legal advice.
              All parties should obtain independent legal advice from a qualified solicitor before signing.
              This deed is subject to {clauses.contractActRef}.
              {"\n"}Generated: {format(data.generatedAt, "d MMMM yyyy 'at' h:mm a")}
              {data.platformAbn ? `\nOptionFlow ABN: ${data.platformAbn}` : ""}
            </Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Call Option Deed — {data.propertyAddress} — Page 1
        </Text>
      </Page>

      {/* Main Deed */}
      <Page size="A4" style={styles.page} wrap>
        {/* Recitals */}
        <Text style={styles.sectionHeading}>RECITALS</Text>

        <Text style={styles.para}>
          A. The Grantor is the registered proprietor of the land described as {data.propertyAddress}, {data.suburb}, {data.state} {data.postcode}
          {data.titleReference ? ` (Title Reference: ${data.titleReference})` : ""}
          {data.lotNumber ? `, Lot ${data.lotNumber}` : ""}
          {data.planNumber ? ` ${data.planNumber}` : ""} (the <Text style={styles.bold}>Property</Text>).
        </Text>

        <Text style={styles.para}>
          B. The Grantor has agreed to grant to the Grantee an exclusive call option to purchase the Property on the terms and conditions set out in this deed.
        </Text>

        <Text style={styles.para}>
          C. The Grantee has agreed to pay the Option Fee to the Grantor in consideration for the grant of this option.
        </Text>

        <Text style={styles.sectionHeading}>OPERATIVE PROVISIONS</Text>

        <Text style={styles.clauseHeading}>1. GRANT OF OPTION</Text>
        <Text style={styles.para}>
          1.1 In consideration of the Option Fee paid by the Grantee to the Grantor (receipt of which is hereby acknowledged), the Grantor hereby grants to the Grantee an exclusive call option to purchase the Property at the Option Price, exercisable during the Option Period on the terms and conditions set out in this deed (<Text style={styles.bold}>Call Option</Text>).
        </Text>
        <Text style={styles.para}>
          1.2 The Call Option is personal to the Grantee and may not be assigned or transferred without the prior written consent of the Grantor, except that the Grantee may assign its rights under this deed to a related entity or by way of an assignment deed executed in accordance with clause 5 below.
        </Text>

        <Text style={styles.clauseHeading}>2. OPTION PERIOD</Text>
        <Text style={styles.para}>
          2.1 The option period commences on <Text style={styles.bold}>{format(data.commencementDate, "d MMMM yyyy")}</Text> and expires at 5:00 PM on <Text style={styles.bold}>{format(data.expiryDate, "d MMMM yyyy")}</Text> (<Text style={styles.bold}>Option Period</Text>), unless earlier exercised or terminated in accordance with this deed.
        </Text>
        {data.extensionDays && data.extensionFeeAmount && (
          <Text style={styles.para}>
            2.2 The Grantee may extend the Option Period by {data.extensionDays} days by paying an additional extension fee of {formatAud(data.extensionFeeAmount)} to the Grantor prior to the expiry of the initial Option Period.
          </Text>
        )}

        <Text style={styles.clauseHeading}>3. OPTION FEE AND OPTION PRICE</Text>
        <Text style={styles.para}>
          3.1 The <Text style={styles.bold}>Option Fee</Text> is <Text style={styles.amountHighlight}>{formatAud(data.optionFeeAmount)}</Text> (inclusive of GST if applicable). The Option Fee is non-refundable, except as expressly provided in this deed.
        </Text>
        <Text style={styles.para}>
          3.2 The <Text style={styles.bold}>Option Price</Text> is <Text style={styles.amountHighlight}>{formatAud(data.optionPrice)}</Text> (inclusive of GST if applicable).
        </Text>
        <Text style={styles.para}>
          3.3 If the Grantee exercises the Call Option, the Option Fee will be applied toward the Option Price at settlement.
        </Text>

        <Text style={styles.clauseHeading}>4. EXERCISE OF OPTION</Text>
        <Text style={styles.para}>
          4.1 The Grantee may exercise the Call Option at any time during the Option Period by delivering written notice to the Grantor.
        </Text>
        <Text style={styles.para}>
          4.2 Upon exercise, the parties shall be bound to complete the sale of the Property at the Option Price on the terms set out in this deed and any attached Contract of Sale.
        </Text>

        <Text style={styles.clauseHeading}>5. ASSIGNMENT OF OPTION</Text>
        <Text style={styles.para}>
          5.1 Subject to clause 1.2, the Grantee may at any time during the Option Period assign its rights under this deed to a third party (<Text style={styles.bold}>Assignee</Text>) by executing an Assignment Deed in a form approved by the Grantor (such approval not to be unreasonably withheld).
        </Text>
        <Text style={styles.para}>
          5.2 Upon execution of an Assignment Deed, the Assignee shall take on all rights and obligations of the Grantee under this deed in respect of the Call Option.
        </Text>

        <Text style={styles.clauseHeading}>6. GRANTOR'S OBLIGATIONS</Text>
        <Text style={styles.para}>
          6.1 During the Option Period, the Grantor must not: (a) sell, transfer, or otherwise dispose of the Property; (b) create or allow any encumbrance over the Property without the Grantee's written consent; (c) take any action that would materially adversely affect the value of the Property.
        </Text>

        <Text style={styles.clauseHeading}>7. STAMP DUTY AND TAXES</Text>
        <Text style={styles.para}>{clauses.stampDutyNote}</Text>
        <Text style={styles.para}>{clauses.landTaxNote}</Text>

        {clauses.coolingOffPeriod && (
          <>
            <Text style={styles.clauseHeading}>8. COOLING-OFF</Text>
            <Text style={styles.para}>{clauses.coolingOffPeriod}</Text>
          </>
        )}

        <Text style={styles.clauseHeading}>{clauses.coolingOffPeriod ? "9" : "8"}. TITLE AND PLANNING</Text>
        <Text style={styles.para}>{clauses.titleSystemNote}</Text>
        <Text style={styles.para}>
          Any {clauses.planningReferenceLabel} applications or planning investigations shall be at the Grantee&apos;s cost and risk. The Grantor agrees to reasonably cooperate with such investigations during the Option Period.
        </Text>

        <Text style={styles.clauseHeading}>{clauses.coolingOffPeriod ? "10" : "9"}. NOTICES</Text>
        <Text style={styles.para}>
          All notices must be in writing and delivered by email (with confirmation of receipt) or registered post to the addresses set out on the cover page of this deed.
        </Text>

        {clauses.additionalDisclosures.map((disc, i) => (
          <Text key={i} style={styles.para}>{disc}</Text>
        ))}

        {data.specialConditions && (
          <>
            <Text style={styles.sectionHeading}>SPECIAL CONDITIONS</Text>
            <Text style={styles.para}>{data.specialConditions}</Text>
          </>
        )}

        <Text style={styles.sectionHeading}>EXECUTION</Text>
        <Text style={styles.small}>{clauses.witnessRequirements}</Text>

        <View style={{ marginTop: 20, flexDirection: "row", gap: 40 }}>
          <View style={{ flex: 1 }}>
            <Text style={[styles.bold, { fontSize: 10, marginBottom: 8 }]}>SIGNED by GRANTOR</Text>
            <Text style={[styles.small, { marginBottom: 2 }]}>{data.grantor_legalName}</Text>
            {data.grantor_abn && <Text style={styles.small}>ABN: {data.grantor_abn}</Text>}
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Signature / Authorised Signatory</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Full name (print)</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Date</Text>
            <View style={{ marginTop: 16 }}>
              <Text style={[styles.small, { marginBottom: 2 }]}>Witness (must not be a party)</Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Witness signature</Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Witness full name (print)</Text>
            </View>
          </View>

          <View style={{ flex: 1 }}>
            <Text style={[styles.bold, { fontSize: 10, marginBottom: 8 }]}>SIGNED by GRANTEE</Text>
            <Text style={[styles.small, { marginBottom: 2 }]}>{data.grantee_legalName}</Text>
            {data.grantee_abn && <Text style={styles.small}>ABN: {data.grantee_abn}</Text>}
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Signature / Authorised Signatory</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Full name (print)</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureLabel}>Date</Text>
            <View style={{ marginTop: 16 }}>
              <Text style={[styles.small, { marginBottom: 2 }]}>Witness (must not be a party)</Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Witness signature</Text>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Witness full name (print)</Text>
            </View>
          </View>
        </View>

        <Text
          style={styles.footer}
          render={() => `Call Option Deed — ${data.propertyAddress} — Generated by OptionFlow`}
          fixed
        />
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
          fixed
        />
      </Page>
    </Document>
  );
}
